/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.beardedhen.androidbootstrap;

public final class R {
    public static final class attr {
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int bb_gradient=0x7f010005;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int bb_icon_left=0x7f010001;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int bb_icon_right=0x7f010002;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int bb_roundedCorners=0x7f010003;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int bb_size=0x7f010004;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int bb_type=0x7f010000;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int be_roundedCorners=0x7f010006;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int be_state=0x7f010007;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int bootstrapButtonStyle=0x7f010008;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int bootstrapEditTextStyle=0x7f010009;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int bootstrapHeadingStyle=0x7f01000a;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int bt_height=0x7f01000e;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int bt_image=0x7f01000c;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int bt_inside_padding=0x7f01000f;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int bt_roundedCorners=0x7f01000b;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int bt_test=0x7f010010;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int bt_width=0x7f01000d;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int fa_icon=0x7f010011;
    }
    public static final class color {
        public static int black=0x7f040000;
        public static int button_danger=0x7f040001;
        public static int button_danger_disabled=0x7f040002;
        public static int button_danger_disabled_edge=0x7f040003;
        public static int button_danger_edge=0x7f040004;
        public static int button_danger_gradient_border=0x7f040005;
        public static int button_danger_gradient_dark=0x7f040006;
        public static int button_danger_gradient_light=0x7f040007;
        public static int button_danger_gradient_medium=0x7f040008;
        public static int button_danger_gradient_pressed_shadow=0x7f040009;
        public static int button_danger_pressed=0x7f04000a;
        public static int button_danger_pressed_edge=0x7f04000b;
        public static int button_default=0x7f04000c;
        public static int button_default_disabled=0x7f04000d;
        public static int button_default_disabled_edge=0x7f04000e;
        public static int button_default_edge=0x7f04000f;
        public static int button_default_gradient_border=0x7f040010;
        public static int button_default_gradient_dark=0x7f040011;
        public static int button_default_gradient_light=0x7f040012;
        public static int button_default_gradient_medium=0x7f040013;
        public static int button_default_gradient_pressed_shadow=0x7f040014;
        public static int button_default_pressed=0x7f040015;
        public static int button_default_pressed_edge=0x7f040016;
        public static int button_edittext_border=0x7f040017;
        public static int button_edittext_disabled=0x7f040018;
        public static int button_info=0x7f040019;
        public static int button_info_disabled=0x7f04001a;
        public static int button_info_disabled_edge=0x7f04001b;
        public static int button_info_edge=0x7f04001c;
        public static int button_info_gradient_border=0x7f04001d;
        public static int button_info_gradient_dark=0x7f04001e;
        public static int button_info_gradient_light=0x7f04001f;
        public static int button_info_gradient_medium=0x7f040020;
        public static int button_info_gradient_pressed_shadow=0x7f040021;
        public static int button_info_pressed=0x7f040022;
        public static int button_info_pressed_edge=0x7f040023;
        public static int button_inverse=0x7f040024;
        public static int button_inverse_disabled=0x7f040025;
        public static int button_inverse_disabled_edge=0x7f040026;
        public static int button_inverse_edge=0x7f040027;
        public static int button_inverse_gradient_border=0x7f040028;
        public static int button_inverse_gradient_dark=0x7f040029;
        public static int button_inverse_gradient_light=0x7f04002a;
        public static int button_inverse_gradient_medium=0x7f04002b;
        public static int button_inverse_gradient_pressed_shadow=0x7f04002c;
        public static int button_inverse_pressed=0x7f04002d;
        public static int button_inverse_pressed_edge=0x7f04002e;
        public static int button_primary=0x7f04002f;
        public static int button_primary_disabled=0x7f040030;
        public static int button_primary_disabled_edge=0x7f040031;
        public static int button_primary_edge=0x7f040032;
        public static int button_primary_gradient_border=0x7f040033;
        public static int button_primary_gradient_dark=0x7f040034;
        public static int button_primary_gradient_light=0x7f040035;
        public static int button_primary_gradient_medium=0x7f040036;
        public static int button_primary_gradient_pressed_shadow=0x7f040037;
        public static int button_primary_pressed=0x7f040038;
        public static int button_primary_pressed_edge=0x7f040039;
        public static int button_purple=0x7f04003a;
        public static int button_purple_disabled=0x7f04003b;
        public static int button_purple_disabled_edge=0x7f04003c;
        public static int button_purple_edge=0x7f04003d;
        public static int button_purple_pressed=0x7f04003e;
        public static int button_purple_pressed_edge=0x7f04003f;
        public static int button_success=0x7f040040;
        public static int button_success_disabled=0x7f040041;
        public static int button_success_disabled_edge=0x7f040042;
        public static int button_success_edge=0x7f040043;
        public static int button_success_gradient_border=0x7f040044;
        public static int button_success_gradient_dark=0x7f040045;
        public static int button_success_gradient_light=0x7f040046;
        public static int button_success_gradient_medium=0x7f040047;
        public static int button_success_gradient_pressed_shadow=0x7f040048;
        public static int button_success_pressed=0x7f040049;
        public static int button_success_pressed_edge=0x7f04004a;
        public static int button_warning=0x7f04004b;
        public static int button_warning_disabled=0x7f04004c;
        public static int button_warning_disabled_edge=0x7f04004d;
        public static int button_warning_edge=0x7f04004e;
        public static int button_warning_gradient_border=0x7f04004f;
        public static int button_warning_gradient_dark=0x7f040050;
        public static int button_warning_gradient_light=0x7f040051;
        public static int button_warning_gradient_medium=0x7f040052;
        public static int button_warning_gradient_pressed_shadow=0x7f040053;
        public static int button_warning_pressed=0x7f040054;
        public static int button_warning_pressed_edge=0x7f040055;
        public static int thumbnail_background=0x7f040056;
        public static int thumbnail_border=0x7f040057;
        public static int thumbnail_font=0x7f040058;
        public static int thumbnail_placeholder=0x7f040059;
        public static int white=0x7f04005a;
    }
    public static final class dimen {
        public static int activity_horizontal_margin=0x7f050000;
        public static int activity_vertical_margin=0x7f050001;
        public static int button_rounded_corner_radius=0x7f050002;
        public static int font_large=0x7f050003;
        public static int font_medium=0x7f050004;
        public static int font_micro=0x7f050005;
        public static int font_small=0x7f050006;
        public static int margin_large=0x7f050007;
        public static int margin_medium=0x7f050008;
        public static int margin_small=0x7f050009;
        public static int padding_large=0x7f05000a;
        public static int padding_medium=0x7f05000b;
        public static int padding_small=0x7f05000c;
        public static int thumbnail_rounded_corner_radius=0x7f05000d;
    }
    public static final class drawable {
        public static int button_danger=0x7f020000;
        public static int button_danger_gradient=0x7f020001;
        public static int button_danger_gradient_rounded=0x7f020002;
        public static int button_danger_rounded=0x7f020003;
        public static int button_default=0x7f020004;
        public static int button_default_gradient=0x7f020005;
        public static int button_default_gradient_rounded=0x7f020006;
        public static int button_default_rounded=0x7f020007;
        public static int button_info=0x7f020008;
        public static int button_info_gradient=0x7f020009;
        public static int button_info_gradient_rounded=0x7f02000a;
        public static int button_info_rounded=0x7f02000b;
        public static int button_inverse=0x7f02000c;
        public static int button_inverse_gradient=0x7f02000d;
        public static int button_inverse_gradient_rounded=0x7f02000e;
        public static int button_inverse_rounded=0x7f02000f;
        public static int button_primary=0x7f020010;
        public static int button_primary_gradient=0x7f020011;
        public static int button_primary_gradient_rounded=0x7f020012;
        public static int button_primary_rounded=0x7f020013;
        public static int button_purple=0x7f020014;
        public static int button_purple_gradient=0x7f020015;
        public static int button_purple_gradient_rounded=0x7f020016;
        public static int button_purple_rounded=0x7f020017;
        public static int button_success=0x7f020018;
        public static int button_success_gradient=0x7f020019;
        public static int button_success_gradient_rounded=0x7f02001a;
        public static int button_success_rounded=0x7f02001b;
        public static int button_warning=0x7f02001c;
        public static int button_warning_gradient=0x7f02001d;
        public static int button_warning_gradient_rounded=0x7f02001e;
        public static int button_warning_rounded=0x7f02001f;
        public static int edittext_background=0x7f020020;
        public static int edittext_background_danger=0x7f020021;
        public static int edittext_background_rounded=0x7f020022;
        public static int edittext_background_rounded_danger=0x7f020023;
        public static int edittext_background_rounded_success=0x7f020024;
        public static int edittext_background_rounded_warning=0x7f020025;
        public static int edittext_background_success=0x7f020026;
        public static int edittext_background_warning=0x7f020027;
        public static int ic_launcher=0x7f020028;
        public static int thumbnail_container_rounded=0x7f020029;
        public static int thumbnail_container_square=0x7f02002a;
        public static int thumbnail_placeholder_default=0x7f02002b;
    }
    public static final class id {
        public static int action_settings=0x7f090006;
        public static int container=0x7f090003;
        public static int dimensionsLabel=0x7f090005;
        public static int layout=0x7f090000;
        public static int lblText=0x7f090002;
        public static int placeholder=0x7f090004;
        public static int txtText=0x7f090001;
    }
    public static final class layout {
        public static int button=0x7f030000;
        public static int edittext=0x7f030001;
        public static int font_awesome_text=0x7f030002;
        public static int thumbnail=0x7f030003;
    }
    public static final class menu {
        public static int main=0x7f080000;
    }
    public static final class string {
        public static int action_settings=0x7f060000;
        public static int app_name=0x7f060001;
        public static int hello_world=0x7f060002;
    }
    public static final class style {
        /** 
            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        
 API 11 theme customizations can go here. 
 API 14 theme customizations can go here. 
         */
        public static int AppBaseTheme=0x7f070000;
        public static int BootstrapButton=0x7f070001;
        public static int BootstrapEditText=0x7f070002;
        public static int BootstrapTypographyHeading=0x7f070003;
        public static int Theme_BootstrapLight=0x7f070004;
    }
    public static final class styleable {
        /** Attributes that can be used with a BootstrapButton.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #BootstrapButton_bb_gradient com.beardedhen.androidbootstrap:bb_gradient}</code></td><td></td></tr>
           <tr><td><code>{@link #BootstrapButton_bb_icon_left com.beardedhen.androidbootstrap:bb_icon_left}</code></td><td></td></tr>
           <tr><td><code>{@link #BootstrapButton_bb_icon_right com.beardedhen.androidbootstrap:bb_icon_right}</code></td><td></td></tr>
           <tr><td><code>{@link #BootstrapButton_bb_roundedCorners com.beardedhen.androidbootstrap:bb_roundedCorners}</code></td><td></td></tr>
           <tr><td><code>{@link #BootstrapButton_bb_size com.beardedhen.androidbootstrap:bb_size}</code></td><td></td></tr>
           <tr><td><code>{@link #BootstrapButton_bb_type com.beardedhen.androidbootstrap:bb_type}</code></td><td></td></tr>
           </table>
           @see #BootstrapButton_bb_gradient
           @see #BootstrapButton_bb_icon_left
           @see #BootstrapButton_bb_icon_right
           @see #BootstrapButton_bb_roundedCorners
           @see #BootstrapButton_bb_size
           @see #BootstrapButton_bb_type
         */
        public static final int[] BootstrapButton = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003,
            0x7f010004, 0x7f010005
        };
        /**
          <p>This symbol is the offset where the {@link com.beardedhen.androidbootstrap.R.attr#bb_gradient}
          attribute's value can be found in the {@link #BootstrapButton} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.beardedhen.androidbootstrap:bb_gradient
        */
        public static final int BootstrapButton_bb_gradient = 5;
        /**
          <p>This symbol is the offset where the {@link com.beardedhen.androidbootstrap.R.attr#bb_icon_left}
          attribute's value can be found in the {@link #BootstrapButton} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.beardedhen.androidbootstrap:bb_icon_left
        */
        public static final int BootstrapButton_bb_icon_left = 1;
        /**
          <p>This symbol is the offset where the {@link com.beardedhen.androidbootstrap.R.attr#bb_icon_right}
          attribute's value can be found in the {@link #BootstrapButton} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.beardedhen.androidbootstrap:bb_icon_right
        */
        public static final int BootstrapButton_bb_icon_right = 2;
        /**
          <p>This symbol is the offset where the {@link com.beardedhen.androidbootstrap.R.attr#bb_roundedCorners}
          attribute's value can be found in the {@link #BootstrapButton} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.beardedhen.androidbootstrap:bb_roundedCorners
        */
        public static final int BootstrapButton_bb_roundedCorners = 3;
        /**
          <p>This symbol is the offset where the {@link com.beardedhen.androidbootstrap.R.attr#bb_size}
          attribute's value can be found in the {@link #BootstrapButton} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.beardedhen.androidbootstrap:bb_size
        */
        public static final int BootstrapButton_bb_size = 4;
        /**
          <p>This symbol is the offset where the {@link com.beardedhen.androidbootstrap.R.attr#bb_type}
          attribute's value can be found in the {@link #BootstrapButton} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.beardedhen.androidbootstrap:bb_type
        */
        public static final int BootstrapButton_bb_type = 0;
        /** Attributes that can be used with a BootstrapEditText.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #BootstrapEditText_android_enabled android:enabled}</code></td><td></td></tr>
           <tr><td><code>{@link #BootstrapEditText_android_hint android:hint}</code></td><td></td></tr>
           <tr><td><code>{@link #BootstrapEditText_android_text android:text}</code></td><td></td></tr>
           <tr><td><code>{@link #BootstrapEditText_android_textSize android:textSize}</code></td><td></td></tr>
           <tr><td><code>{@link #BootstrapEditText_be_roundedCorners com.beardedhen.androidbootstrap:be_roundedCorners}</code></td><td></td></tr>
           <tr><td><code>{@link #BootstrapEditText_be_state com.beardedhen.androidbootstrap:be_state}</code></td><td></td></tr>
           </table>
           @see #BootstrapEditText_android_enabled
           @see #BootstrapEditText_android_hint
           @see #BootstrapEditText_android_text
           @see #BootstrapEditText_android_textSize
           @see #BootstrapEditText_be_roundedCorners
           @see #BootstrapEditText_be_state
         */
        public static final int[] BootstrapEditText = {
            0x0101000e, 0x01010095, 0x0101014f, 0x01010150,
            0x7f010006, 0x7f010007
        };
        /**
          <p>This symbol is the offset where the {@link android.R.attr#enabled}
          attribute's value can be found in the {@link #BootstrapEditText} array.
          @attr name android:enabled
        */
        public static final int BootstrapEditText_android_enabled = 0;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#hint}
          attribute's value can be found in the {@link #BootstrapEditText} array.
          @attr name android:hint
        */
        public static final int BootstrapEditText_android_hint = 3;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#text}
          attribute's value can be found in the {@link #BootstrapEditText} array.
          @attr name android:text
        */
        public static final int BootstrapEditText_android_text = 2;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#textSize}
          attribute's value can be found in the {@link #BootstrapEditText} array.
          @attr name android:textSize
        */
        public static final int BootstrapEditText_android_textSize = 1;
        /**
          <p>This symbol is the offset where the {@link com.beardedhen.androidbootstrap.R.attr#be_roundedCorners}
          attribute's value can be found in the {@link #BootstrapEditText} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.beardedhen.androidbootstrap:be_roundedCorners
        */
        public static final int BootstrapEditText_be_roundedCorners = 4;
        /**
          <p>This symbol is the offset where the {@link com.beardedhen.androidbootstrap.R.attr#be_state}
          attribute's value can be found in the {@link #BootstrapEditText} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.beardedhen.androidbootstrap:be_state
        */
        public static final int BootstrapEditText_be_state = 5;
        /** Attributes that can be used with a BootstrapTheme.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #BootstrapTheme_bootstrapButtonStyle com.beardedhen.androidbootstrap:bootstrapButtonStyle}</code></td><td></td></tr>
           <tr><td><code>{@link #BootstrapTheme_bootstrapEditTextStyle com.beardedhen.androidbootstrap:bootstrapEditTextStyle}</code></td><td></td></tr>
           <tr><td><code>{@link #BootstrapTheme_bootstrapHeadingStyle com.beardedhen.androidbootstrap:bootstrapHeadingStyle}</code></td><td></td></tr>
           </table>
           @see #BootstrapTheme_bootstrapButtonStyle
           @see #BootstrapTheme_bootstrapEditTextStyle
           @see #BootstrapTheme_bootstrapHeadingStyle
         */
        public static final int[] BootstrapTheme = {
            0x7f010008, 0x7f010009, 0x7f01000a
        };
        /**
          <p>This symbol is the offset where the {@link com.beardedhen.androidbootstrap.R.attr#bootstrapButtonStyle}
          attribute's value can be found in the {@link #BootstrapTheme} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.beardedhen.androidbootstrap:bootstrapButtonStyle
        */
        public static final int BootstrapTheme_bootstrapButtonStyle = 0;
        /**
          <p>This symbol is the offset where the {@link com.beardedhen.androidbootstrap.R.attr#bootstrapEditTextStyle}
          attribute's value can be found in the {@link #BootstrapTheme} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.beardedhen.androidbootstrap:bootstrapEditTextStyle
        */
        public static final int BootstrapTheme_bootstrapEditTextStyle = 1;
        /**
          <p>This symbol is the offset where the {@link com.beardedhen.androidbootstrap.R.attr#bootstrapHeadingStyle}
          attribute's value can be found in the {@link #BootstrapTheme} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.beardedhen.androidbootstrap:bootstrapHeadingStyle
        */
        public static final int BootstrapTheme_bootstrapHeadingStyle = 2;
        /** Attributes that can be used with a BootstrapThumbnail.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #BootstrapThumbnail_android_text android:text}</code></td><td></td></tr>
           <tr><td><code>{@link #BootstrapThumbnail_bt_height com.beardedhen.androidbootstrap:bt_height}</code></td><td></td></tr>
           <tr><td><code>{@link #BootstrapThumbnail_bt_image com.beardedhen.androidbootstrap:bt_image}</code></td><td></td></tr>
           <tr><td><code>{@link #BootstrapThumbnail_bt_inside_padding com.beardedhen.androidbootstrap:bt_inside_padding}</code></td><td></td></tr>
           <tr><td><code>{@link #BootstrapThumbnail_bt_roundedCorners com.beardedhen.androidbootstrap:bt_roundedCorners}</code></td><td></td></tr>
           <tr><td><code>{@link #BootstrapThumbnail_bt_width com.beardedhen.androidbootstrap:bt_width}</code></td><td></td></tr>
           </table>
           @see #BootstrapThumbnail_android_text
           @see #BootstrapThumbnail_bt_height
           @see #BootstrapThumbnail_bt_image
           @see #BootstrapThumbnail_bt_inside_padding
           @see #BootstrapThumbnail_bt_roundedCorners
           @see #BootstrapThumbnail_bt_width
         */
        public static final int[] BootstrapThumbnail = {
            0x0101014f, 0x7f01000b, 0x7f01000c, 0x7f01000d,
            0x7f01000e, 0x7f01000f
        };
        /**
          <p>This symbol is the offset where the {@link android.R.attr#text}
          attribute's value can be found in the {@link #BootstrapThumbnail} array.
          @attr name android:text
        */
        public static final int BootstrapThumbnail_android_text = 0;
        /**
          <p>This symbol is the offset where the {@link com.beardedhen.androidbootstrap.R.attr#bt_height}
          attribute's value can be found in the {@link #BootstrapThumbnail} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.beardedhen.androidbootstrap:bt_height
        */
        public static final int BootstrapThumbnail_bt_height = 4;
        /**
          <p>This symbol is the offset where the {@link com.beardedhen.androidbootstrap.R.attr#bt_image}
          attribute's value can be found in the {@link #BootstrapThumbnail} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.beardedhen.androidbootstrap:bt_image
        */
        public static final int BootstrapThumbnail_bt_image = 2;
        /**
          <p>This symbol is the offset where the {@link com.beardedhen.androidbootstrap.R.attr#bt_inside_padding}
          attribute's value can be found in the {@link #BootstrapThumbnail} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.beardedhen.androidbootstrap:bt_inside_padding
        */
        public static final int BootstrapThumbnail_bt_inside_padding = 5;
        /**
          <p>This symbol is the offset where the {@link com.beardedhen.androidbootstrap.R.attr#bt_roundedCorners}
          attribute's value can be found in the {@link #BootstrapThumbnail} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.beardedhen.androidbootstrap:bt_roundedCorners
        */
        public static final int BootstrapThumbnail_bt_roundedCorners = 1;
        /**
          <p>This symbol is the offset where the {@link com.beardedhen.androidbootstrap.R.attr#bt_width}
          attribute's value can be found in the {@link #BootstrapThumbnail} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.beardedhen.androidbootstrap:bt_width
        */
        public static final int BootstrapThumbnail_bt_width = 3;
        /** Attributes that can be used with a BootstrapTypography.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #BootstrapTypography_bt_test com.beardedhen.androidbootstrap:bt_test}</code></td><td></td></tr>
           </table>
           @see #BootstrapTypography_bt_test
         */
        public static final int[] BootstrapTypography = {
            0x7f010010
        };
        /**
          <p>This symbol is the offset where the {@link com.beardedhen.androidbootstrap.R.attr#bt_test}
          attribute's value can be found in the {@link #BootstrapTypography} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.beardedhen.androidbootstrap:bt_test
        */
        public static final int BootstrapTypography_bt_test = 0;
        /** Attributes that can be used with a FontAwesomeText.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #FontAwesomeText_android_textColor android:textColor}</code></td><td></td></tr>
           <tr><td><code>{@link #FontAwesomeText_android_textSize android:textSize}</code></td><td></td></tr>
           <tr><td><code>{@link #FontAwesomeText_fa_icon com.beardedhen.androidbootstrap:fa_icon}</code></td><td></td></tr>
           </table>
           @see #FontAwesomeText_android_textColor
           @see #FontAwesomeText_android_textSize
           @see #FontAwesomeText_fa_icon
         */
        public static final int[] FontAwesomeText = {
            0x01010095, 0x01010098, 0x7f010011
        };
        /**
          <p>This symbol is the offset where the {@link android.R.attr#textColor}
          attribute's value can be found in the {@link #FontAwesomeText} array.
          @attr name android:textColor
        */
        public static final int FontAwesomeText_android_textColor = 1;
        /**
          <p>This symbol is the offset where the {@link android.R.attr#textSize}
          attribute's value can be found in the {@link #FontAwesomeText} array.
          @attr name android:textSize
        */
        public static final int FontAwesomeText_android_textSize = 0;
        /**
          <p>This symbol is the offset where the {@link com.beardedhen.androidbootstrap.R.attr#fa_icon}
          attribute's value can be found in the {@link #FontAwesomeText} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.beardedhen.androidbootstrap:fa_icon
        */
        public static final int FontAwesomeText_fa_icon = 2;
    };
}
