package com.beardedhen.androidbootstrap;

import android.content.Context;

import com.beardedhen.androidbootstrap.font.FontAwesomeIcon;
import com.beardedhen.androidbootstrap.support.BootstrapText;

import java.util.HashMap;
import java.util.Map;

import static com.beardedhen.androidbootstrap.font.FontAwesomeIcon.*;

/**
 * Resolves markdown strings using FA codes and produces BootstrapText instances.
 */
public class MarkdownResolver {

    /**
     * Resolves markdown to produce a BootstrapText instance. e.g. "{fa_android}" would be replaced
     * with the appropriate FontAwesome character and a SpannableString producec.
     *
     * @param context the current context
     * @param markdown the markdown string
     * @return a constructed BootstrapText
     */
    public static BootstrapText resolveMarkdown(Context context, String markdown) {
        if (markdown == null) {
            return null;
        }
        else { // detect {fa_*} and split into spannable, ignore escaped chars
            BootstrapText.Builder builder = new BootstrapText.Builder(context);

            int lastAddedIndex = 0;
            int startIndex = -1;
            int endIndex = -1;

            for (int i = 0; i < markdown.length(); i++) {
                char c = markdown.charAt(i);

                if (c == '\\') { // escape sequence, ignore next char
                    i+= 2;
                    continue;
                }

                if (c == '{') {
                    startIndex = i;
                }
                else if (c == '}') {
                    endIndex = i;
                }

                if (startIndex != -1 && endIndex != -1) { // recognised markdown string

                    if (startIndex >= 0 && endIndex < markdown.length()) {
                        String text = markdown.substring(startIndex + 1, endIndex);

                        if (text.matches("fa_[a-z_0-9]+")) { // text is FontAwesome code
                            builder.addText(markdown.substring(lastAddedIndex, startIndex));
                            builder.addIcon(resolveFontAwesomeIcon(text));
                            lastAddedIndex = endIndex + 1;
                        }
                    }
                    startIndex = -1;
                    endIndex = -1;
                }
            }
            return builder.addText(markdown.substring(lastAddedIndex, markdown.length())).build();
        }
    }

    private static FontAwesomeIcon resolveFontAwesomeIcon(CharSequence markdown) {
        FontAwesomeIcon fontAwesomeIcon = MAP.get(markdown);

        if (fontAwesomeIcon == null) {
            String message = String.format("FontAwesome icon code not mapped for '%s', please ensure " +
                    "that the code exists and any hyphens are replaced with underscores", markdown);

            throw new IllegalArgumentException(message);
        }
        else {
            return fontAwesomeIcon;
        }
    }

    private static Map<CharSequence, FontAwesomeIcon> MAP = new HashMap<>();

    static {
        MAP.put("fa_adjust", FA_ADJUST);
        MAP.put("fa_adn", FA_ADN);
        MAP.put("fa_align_center", FA_ALIGN_CENTER);
        MAP.put("fa_align_justify", FA_ALIGN_JUSTIFY);
        MAP.put("fa_align_left", FA_ALIGN_LEFT);
        MAP.put("fa_align_right", FA_ALIGN_RIGHT);
        MAP.put("fa_amazon", FA_AMAZON);
        MAP.put("fa_ambulance", FA_AMBULANCE);
        MAP.put("fa_anchor", FA_ANCHOR);
        MAP.put("fa_android", FA_ANDROID);
        MAP.put("fa_angellist", FA_ANGELLIST);
        MAP.put("fa_angle_double_down", FA_ANGLE_DOUBLE_DOWN);
        MAP.put("fa_angle_double_left", FA_ANGLE_DOUBLE_LEFT);
        MAP.put("fa_angle_double_right", FA_ANGLE_DOUBLE_RIGHT);
        MAP.put("fa_angle_double_up", FA_ANGLE_DOUBLE_UP);
        MAP.put("fa_angle_down", FA_ANGLE_DOWN);
        MAP.put("fa_angle_left", FA_ANGLE_LEFT);
        MAP.put("fa_angle_right", FA_ANGLE_RIGHT);
        MAP.put("fa_angle_up", FA_ANGLE_UP);
        MAP.put("fa_apple", FA_APPLE);
        MAP.put("fa_archive", FA_ARCHIVE);
        MAP.put("fa_area_chart", FA_AREA_CHART);
        MAP.put("fa_arrow_circle_down", FA_ARROW_CIRCLE_DOWN);
        MAP.put("fa_arrow_circle_left", FA_ARROW_CIRCLE_LEFT);
        MAP.put("fa_arrow_circle_o_down", FA_ARROW_CIRCLE_O_DOWN);
        MAP.put("fa_arrow_circle_o_left", FA_ARROW_CIRCLE_O_LEFT);
        MAP.put("fa_arrow_circle_o_right", FA_ARROW_CIRCLE_O_RIGHT);
        MAP.put("fa_arrow_circle_o_up", FA_ARROW_CIRCLE_O_UP);
        MAP.put("fa_arrow_circle_right", FA_ARROW_CIRCLE_RIGHT);
        MAP.put("fa_arrow_circle_up", FA_ARROW_CIRCLE_UP);
        MAP.put("fa_arrow_down", FA_ARROW_DOWN);
        MAP.put("fa_arrow_left", FA_ARROW_LEFT);
        MAP.put("fa_arrow_right", FA_ARROW_RIGHT);
        MAP.put("fa_arrow_up", FA_ARROW_UP);
        MAP.put("fa_arrows", FA_ARROWS);
        MAP.put("fa_arrows_alt", FA_ARROWS_ALT);
        MAP.put("fa_arrows_h", FA_ARROWS_H);
        MAP.put("fa_arrows_v", FA_ARROWS_V);
        MAP.put("fa_asterisk", FA_ASTERISK);
        MAP.put("fa_at", FA_AT);
        MAP.put("fa_automobile", FA_AUTOMOBILE);
        MAP.put("fa_backward", FA_BACKWARD);
        MAP.put("fa_balance_scale", FA_BALANCE_SCALE);
        MAP.put("fa_ban", FA_BAN);
        MAP.put("fa_bank", FA_BANK);
        MAP.put("fa_bar_chart", FA_BAR_CHART);
        MAP.put("fa_bar_chart_o", FA_BAR_CHART_O);
        MAP.put("fa_barcode", FA_BARCODE);
        MAP.put("fa_bars", FA_BARS);
        MAP.put("fa_battery_0", FA_BATTERY_0);
        MAP.put("fa_battery_1", FA_BATTERY_1);
        MAP.put("fa_battery_2", FA_BATTERY_2);
        MAP.put("fa_battery_3", FA_BATTERY_3);
        MAP.put("fa_battery_4", FA_BATTERY_4);
        MAP.put("fa_battery_empty", FA_BATTERY_EMPTY);
        MAP.put("fa_battery_full", FA_BATTERY_FULL);
        MAP.put("fa_battery_half", FA_BATTERY_HALF);
        MAP.put("fa_battery_quarter", FA_BATTERY_QUARTER);
        MAP.put("fa_battery_three_quarters", FA_BATTERY_THREE_QUARTERS);
        MAP.put("fa_bed", FA_BED);
        MAP.put("fa_beer", FA_BEER);
        MAP.put("fa_behance", FA_BEHANCE);
        MAP.put("fa_behance_square", FA_BEHANCE_SQUARE);
        MAP.put("fa_bell", FA_BELL);
        MAP.put("fa_bell_o", FA_BELL_O);
        MAP.put("fa_bell_slash", FA_BELL_SLASH);
        MAP.put("fa_bell_slash_o", FA_BELL_SLASH_O);
        MAP.put("fa_bicycle", FA_BICYCLE);
        MAP.put("fa_binoculars", FA_BINOCULARS);
        MAP.put("fa_birthday_cake", FA_BIRTHDAY_CAKE);
        MAP.put("fa_bitbucket", FA_BITBUCKET);
        MAP.put("fa_bitbucket_square", FA_BITBUCKET_SQUARE);
        MAP.put("fa_bitcoin", FA_BITCOIN);
        MAP.put("fa_black_tie", FA_BLACK_TIE);
        MAP.put("fa_bold", FA_BOLD);
        MAP.put("fa_bolt", FA_BOLT);
        MAP.put("fa_bomb", FA_BOMB);
        MAP.put("fa_book", FA_BOOK);
        MAP.put("fa_bookmark", FA_BOOKMARK);
        MAP.put("fa_bookmark_o", FA_BOOKMARK_O);
        MAP.put("fa_briefcase", FA_BRIEFCASE);
        MAP.put("fa_btc", FA_BTC);
        MAP.put("fa_bug", FA_BUG);
        MAP.put("fa_building", FA_BUILDING);
        MAP.put("fa_building_o", FA_BUILDING_O);
        MAP.put("fa_bullhorn", FA_BULLHORN);
        MAP.put("fa_bullseye", FA_BULLSEYE);
        MAP.put("fa_bus", FA_BUS);
        MAP.put("fa_buysellads", FA_BUYSELLADS);
        MAP.put("fa_cab", FA_CAB);
        MAP.put("fa_calculator", FA_CALCULATOR);
        MAP.put("fa_calendar", FA_CALENDAR);
        MAP.put("fa_calendar_check_o", FA_CALENDAR_CHECK_O);
        MAP.put("fa_calendar_minus_o", FA_CALENDAR_MINUS_O);
        MAP.put("fa_calendar_o", FA_CALENDAR_O);
        MAP.put("fa_calendar_plus_o", FA_CALENDAR_PLUS_O);
        MAP.put("fa_calendar_times_o", FA_CALENDAR_TIMES_O);
        MAP.put("fa_camera", FA_CAMERA);
        MAP.put("fa_camera_retro", FA_CAMERA_RETRO);
        MAP.put("fa_car", FA_CAR);
        MAP.put("fa_caret_down", FA_CARET_DOWN);
        MAP.put("fa_caret_left", FA_CARET_LEFT);
        MAP.put("fa_caret_right", FA_CARET_RIGHT);
        MAP.put("fa_caret_square_o_down", FA_CARET_SQUARE_O_DOWN);
        MAP.put("fa_caret_square_o_left", FA_CARET_SQUARE_O_LEFT);
        MAP.put("fa_caret_square_o_right", FA_CARET_SQUARE_O_RIGHT);
        MAP.put("fa_caret_square_o_up", FA_CARET_SQUARE_O_UP);
        MAP.put("fa_caret_up", FA_CARET_UP);
        MAP.put("fa_cart_arrow_down", FA_CART_ARROW_DOWN);
        MAP.put("fa_cart_plus", FA_CART_PLUS);
        MAP.put("fa_cc", FA_CC);
        MAP.put("fa_cc_amex", FA_CC_AMEX);
        MAP.put("fa_cc_diners_club", FA_CC_DINERS_CLUB);
        MAP.put("fa_cc_discover", FA_CC_DISCOVER);
        MAP.put("fa_cc_jcb", FA_CC_JCB);
        MAP.put("fa_cc_mastercard", FA_CC_MASTERCARD);
        MAP.put("fa_cc_paypal", FA_CC_PAYPAL);
        MAP.put("fa_cc_stripe", FA_CC_STRIPE);
        MAP.put("fa_cc_visa", FA_CC_VISA);
        MAP.put("fa_certificate", FA_CERTIFICATE);
        MAP.put("fa_chain", FA_CHAIN);
        MAP.put("fa_chain_broken", FA_CHAIN_BROKEN);
        MAP.put("fa_check", FA_CHECK);
        MAP.put("fa_check_circle", FA_CHECK_CIRCLE);
        MAP.put("fa_check_circle_o", FA_CHECK_CIRCLE_O);
        MAP.put("fa_check_square", FA_CHECK_SQUARE);
        MAP.put("fa_check_square_o", FA_CHECK_SQUARE_O);
        MAP.put("fa_chevron_circle_down", FA_CHEVRON_CIRCLE_DOWN);
        MAP.put("fa_chevron_circle_left", FA_CHEVRON_CIRCLE_LEFT);
        MAP.put("fa_chevron_circle_right", FA_CHEVRON_CIRCLE_RIGHT);
        MAP.put("fa_chevron_circle_up", FA_CHEVRON_CIRCLE_UP);
        MAP.put("fa_chevron_down", FA_CHEVRON_DOWN);
        MAP.put("fa_chevron_left", FA_CHEVRON_LEFT);
        MAP.put("fa_chevron_right", FA_CHEVRON_RIGHT);
        MAP.put("fa_chevron_up", FA_CHEVRON_UP);
        MAP.put("fa_child", FA_CHILD);
        MAP.put("fa_chrome", FA_CHROME);
        MAP.put("fa_circle", FA_CIRCLE);
        MAP.put("fa_circle_o", FA_CIRCLE_O);
        MAP.put("fa_circle_o_notch", FA_CIRCLE_O_NOTCH);
        MAP.put("fa_circle_thin", FA_CIRCLE_THIN);
        MAP.put("fa_clipboard", FA_CLIPBOARD);
        MAP.put("fa_clock_o", FA_CLOCK_O);
        MAP.put("fa_clone", FA_CLONE);
        MAP.put("fa_close", FA_CLOSE);
        MAP.put("fa_cloud", FA_CLOUD);
        MAP.put("fa_cloud_download", FA_CLOUD_DOWNLOAD);
        MAP.put("fa_cloud_upload", FA_CLOUD_UPLOAD);
        MAP.put("fa_cny", FA_CNY);
        MAP.put("fa_code", FA_CODE);
        MAP.put("fa_code_fork", FA_CODE_FORK);
        MAP.put("fa_codepen", FA_CODEPEN);
        MAP.put("fa_coffee", FA_COFFEE);
        MAP.put("fa_cog", FA_COG);
        MAP.put("fa_cogs", FA_COGS);
        MAP.put("fa_columns", FA_COLUMNS);
        MAP.put("fa_comment", FA_COMMENT);
        MAP.put("fa_comment_o", FA_COMMENT_O);
        MAP.put("fa_commenting", FA_COMMENTING);
        MAP.put("fa_commenting_o", FA_COMMENTING_O);
        MAP.put("fa_comments", FA_COMMENTS);
        MAP.put("fa_comments_o", FA_COMMENTS_O);
        MAP.put("fa_compass", FA_COMPASS);
        MAP.put("fa_compress", FA_COMPRESS);
        MAP.put("fa_connectdevelop", FA_CONNECTDEVELOP);
        MAP.put("fa_contao", FA_CONTAO);
        MAP.put("fa_copy", FA_COPY);
        MAP.put("fa_copyright", FA_COPYRIGHT);
        MAP.put("fa_creative_commons", FA_CREATIVE_COMMONS);
        MAP.put("fa_credit_card", FA_CREDIT_CARD);
        MAP.put("fa_crop", FA_CROP);
        MAP.put("fa_crosshairs", FA_CROSSHAIRS);
        MAP.put("fa_css3", FA_CSS3);
        MAP.put("fa_cube", FA_CUBE);
        MAP.put("fa_cubes", FA_CUBES);
        MAP.put("fa_cut", FA_CUT);
        MAP.put("fa_cutlery", FA_CUTLERY);
        MAP.put("fa_dashboard", FA_DASHBOARD);
        MAP.put("fa_dashcube", FA_DASHCUBE);
        MAP.put("fa_database", FA_DATABASE);
        MAP.put("fa_dedent", FA_DEDENT);
        MAP.put("fa_delicious", FA_DELICIOUS);
        MAP.put("fa_desktop", FA_DESKTOP);
        MAP.put("fa_deviantart", FA_DEVIANTART);
        MAP.put("fa_diamond", FA_DIAMOND);
        MAP.put("fa_digg", FA_DIGG);
        MAP.put("fa_dollar", FA_DOLLAR);
        MAP.put("fa_dot_circle_o", FA_DOT_CIRCLE_O);
        MAP.put("fa_download", FA_DOWNLOAD);
        MAP.put("fa_dribbble", FA_DRIBBBLE);
        MAP.put("fa_dropbox", FA_DROPBOX);
        MAP.put("fa_drupal", FA_DRUPAL);
        MAP.put("fa_edit", FA_EDIT);
        MAP.put("fa_eject", FA_EJECT);
        MAP.put("fa_ellipsis_h", FA_ELLIPSIS_H);
        MAP.put("fa_ellipsis_v", FA_ELLIPSIS_V);
        MAP.put("fa_empire", FA_EMPIRE);
        MAP.put("fa_envelope", FA_ENVELOPE);
        MAP.put("fa_envelope_o", FA_ENVELOPE_O);
        MAP.put("fa_envelope_square", FA_ENVELOPE_SQUARE);
        MAP.put("fa_eraser", FA_ERASER);
        MAP.put("fa_eur", FA_EUR);
        MAP.put("fa_euro", FA_EURO);
        MAP.put("fa_exchange", FA_EXCHANGE);
        MAP.put("fa_exclamation", FA_EXCLAMATION);
        MAP.put("fa_exclamation_circle", FA_EXCLAMATION_CIRCLE);
        MAP.put("fa_exclamation_triangle", FA_EXCLAMATION_TRIANGLE);
        MAP.put("fa_expand", FA_EXPAND);
        MAP.put("fa_expeditedssl", FA_EXPEDITEDSSL);
        MAP.put("fa_external_link", FA_EXTERNAL_LINK);
        MAP.put("fa_external_link_square", FA_EXTERNAL_LINK_SQUARE);
        MAP.put("fa_eye", FA_EYE);
        MAP.put("fa_eye_slash", FA_EYE_SLASH);
        MAP.put("fa_eyedropper", FA_EYEDROPPER);
        MAP.put("fa_facebook", FA_FACEBOOK);
        MAP.put("fa_facebook_f", FA_FACEBOOK_F);
        MAP.put("fa_facebook_official", FA_FACEBOOK_OFFICIAL);
        MAP.put("fa_facebook_square", FA_FACEBOOK_SQUARE);
        MAP.put("fa_fast_backward", FA_FAST_BACKWARD);
        MAP.put("fa_fast_forward", FA_FAST_FORWARD);
        MAP.put("fa_fax", FA_FAX);
        MAP.put("fa_feed", FA_FEED);
        MAP.put("fa_female", FA_FEMALE);
        MAP.put("fa_fighter_jet", FA_FIGHTER_JET);
        MAP.put("fa_file", FA_FILE);
        MAP.put("fa_file_archive_o", FA_FILE_ARCHIVE_O);
        MAP.put("fa_file_audio_o", FA_FILE_AUDIO_O);
        MAP.put("fa_file_code_o", FA_FILE_CODE_O);
        MAP.put("fa_file_excel_o", FA_FILE_EXCEL_O);
        MAP.put("fa_file_image_o", FA_FILE_IMAGE_O);
        MAP.put("fa_file_movie_o", FA_FILE_MOVIE_O);
        MAP.put("fa_file_o", FA_FILE_O);
        MAP.put("fa_file_pdf_o", FA_FILE_PDF_O);
        MAP.put("fa_file_photo_o", FA_FILE_PHOTO_O);
        MAP.put("fa_file_picture_o", FA_FILE_PICTURE_O);
        MAP.put("fa_file_powerpoint_o", FA_FILE_POWERPOINT_O);
        MAP.put("fa_file_sound_o", FA_FILE_SOUND_O);
        MAP.put("fa_file_text", FA_FILE_TEXT);
        MAP.put("fa_file_text_o", FA_FILE_TEXT_O);
        MAP.put("fa_file_video_o", FA_FILE_VIDEO_O);
        MAP.put("fa_file_word_o", FA_FILE_WORD_O);
        MAP.put("fa_file_zip_o", FA_FILE_ZIP_O);
        MAP.put("fa_files_o", FA_FILES_O);
        MAP.put("fa_film", FA_FILM);
        MAP.put("fa_filter", FA_FILTER);
        MAP.put("fa_fire", FA_FIRE);
        MAP.put("fa_fire_extinguisher", FA_FIRE_EXTINGUISHER);
        MAP.put("fa_firefox", FA_FIREFOX);
        MAP.put("fa_flag", FA_FLAG);
        MAP.put("fa_flag_checkered", FA_FLAG_CHECKERED);
        MAP.put("fa_flag_o", FA_FLAG_O);
        MAP.put("fa_flash", FA_FLASH);
        MAP.put("fa_flask", FA_FLASK);
        MAP.put("fa_flickr", FA_FLICKR);
        MAP.put("fa_floppy_o", FA_FLOPPY_O);
        MAP.put("fa_folder", FA_FOLDER);
        MAP.put("fa_folder_o", FA_FOLDER_O);
        MAP.put("fa_folder_open", FA_FOLDER_OPEN);
        MAP.put("fa_folder_open_o", FA_FOLDER_OPEN_O);
        MAP.put("fa_font", FA_FONT);
        MAP.put("fa_fonticons", FA_FONTICONS);
        MAP.put("fa_forumbee", FA_FORUMBEE);
        MAP.put("fa_forward", FA_FORWARD);
        MAP.put("fa_foursquare", FA_FOURSQUARE);
        MAP.put("fa_frown_o", FA_FROWN_O);
        MAP.put("fa_futbol_o", FA_FUTBOL_O);
        MAP.put("fa_gamepad", FA_GAMEPAD);
        MAP.put("fa_gavel", FA_GAVEL);
        MAP.put("fa_gbp", FA_GBP);
        MAP.put("fa_ge", FA_GE);
        MAP.put("fa_gear", FA_GEAR);
        MAP.put("fa_gears", FA_GEARS);
        MAP.put("fa_genderless", FA_GENDERLESS);
        MAP.put("fa_get_pocket", FA_GET_POCKET);
        MAP.put("fa_gg", FA_GG);
        MAP.put("fa_gg_circle", FA_GG_CIRCLE);
        MAP.put("fa_gift", FA_GIFT);
        MAP.put("fa_git", FA_GIT);
        MAP.put("fa_git_square", FA_GIT_SQUARE);
        MAP.put("fa_github", FA_GITHUB);
        MAP.put("fa_github_alt", FA_GITHUB_ALT);
        MAP.put("fa_github_square", FA_GITHUB_SQUARE);
        MAP.put("fa_gittip", FA_GITTIP);
        MAP.put("fa_glass", FA_GLASS);
        MAP.put("fa_globe", FA_GLOBE);
        MAP.put("fa_google", FA_GOOGLE);
        MAP.put("fa_google_plus", FA_GOOGLE_PLUS);
        MAP.put("fa_google_plus_square", FA_GOOGLE_PLUS_SQUARE);
        MAP.put("fa_google_wallet", FA_GOOGLE_WALLET);
        MAP.put("fa_graduation_cap", FA_GRADUATION_CAP);
        MAP.put("fa_gratipay", FA_GRATIPAY);
        MAP.put("fa_group", FA_GROUP);
        MAP.put("fa_h_square", FA_H_SQUARE);
        MAP.put("fa_hacker_news", FA_HACKER_NEWS);
        MAP.put("fa_hand_grab_o", FA_HAND_GRAB_O);
        MAP.put("fa_hand_lizard_o", FA_HAND_LIZARD_O);
        MAP.put("fa_hand_o_down", FA_HAND_O_DOWN);
        MAP.put("fa_hand_o_left", FA_HAND_O_LEFT);
        MAP.put("fa_hand_o_right", FA_HAND_O_RIGHT);
        MAP.put("fa_hand_o_up", FA_HAND_O_UP);
        MAP.put("fa_hand_paper_o", FA_HAND_PAPER_O);
        MAP.put("fa_hand_peace_o", FA_HAND_PEACE_O);
        MAP.put("fa_hand_pointer_o", FA_HAND_POINTER_O);
        MAP.put("fa_hand_rock_o", FA_HAND_ROCK_O);
        MAP.put("fa_hand_scissors_o", FA_HAND_SCISSORS_O);
        MAP.put("fa_hand_spock_o", FA_HAND_SPOCK_O);
        MAP.put("fa_hand_stop_o", FA_HAND_STOP_O);
        MAP.put("fa_hdd_o", FA_HDD_O);
        MAP.put("fa_header", FA_HEADER);
        MAP.put("fa_headphones", FA_HEADPHONES);
        MAP.put("fa_heart", FA_HEART);
        MAP.put("fa_heart_o", FA_HEART_O);
        MAP.put("fa_heartbeat", FA_HEARTBEAT);
        MAP.put("fa_history", FA_HISTORY);
        MAP.put("fa_home", FA_HOME);
        MAP.put("fa_hospital_o", FA_HOSPITAL_O);
        MAP.put("fa_hotel", FA_HOTEL);
        MAP.put("fa_hourglass", FA_HOURGLASS);
        MAP.put("fa_hourglass_1", FA_HOURGLASS_1);
        MAP.put("fa_hourglass_2", FA_HOURGLASS_2);
        MAP.put("fa_hourglass_3", FA_HOURGLASS_3);
        MAP.put("fa_hourglass_end", FA_HOURGLASS_END);
        MAP.put("fa_hourglass_half", FA_HOURGLASS_HALF);
        MAP.put("fa_hourglass_o", FA_HOURGLASS_O);
        MAP.put("fa_hourglass_start", FA_HOURGLASS_START);
        MAP.put("fa_houzz", FA_HOUZZ);
        MAP.put("fa_html5", FA_HTML5);
        MAP.put("fa_i_cursor", FA_I_CURSOR);
        MAP.put("fa_ils", FA_ILS);
        MAP.put("fa_image", FA_IMAGE);
        MAP.put("fa_inbox", FA_INBOX);
        MAP.put("fa_indent", FA_INDENT);
        MAP.put("fa_industry", FA_INDUSTRY);
        MAP.put("fa_info", FA_INFO);
        MAP.put("fa_info_circle", FA_INFO_CIRCLE);
        MAP.put("fa_inr", FA_INR);
        MAP.put("fa_instagram", FA_INSTAGRAM);
        MAP.put("fa_institution", FA_INSTITUTION);
        MAP.put("fa_internet_explorer", FA_INTERNET_EXPLORER);
        MAP.put("fa_intersex", FA_INTERSEX);
        MAP.put("fa_ioxhost", FA_IOXHOST);
        MAP.put("fa_italic", FA_ITALIC);
        MAP.put("fa_joomla", FA_JOOMLA);
        MAP.put("fa_jpy", FA_JPY);
        MAP.put("fa_jsfiddle", FA_JSFIDDLE);
        MAP.put("fa_key", FA_KEY);
        MAP.put("fa_keyboard_o", FA_KEYBOARD_O);
        MAP.put("fa_krw", FA_KRW);
        MAP.put("fa_language", FA_LANGUAGE);
        MAP.put("fa_laptop", FA_LAPTOP);
        MAP.put("fa_lastfm", FA_LASTFM);
        MAP.put("fa_lastfm_square", FA_LASTFM_SQUARE);
        MAP.put("fa_leaf", FA_LEAF);
        MAP.put("fa_leanpub", FA_LEANPUB);
        MAP.put("fa_legal", FA_LEGAL);
        MAP.put("fa_lemon_o", FA_LEMON_O);
        MAP.put("fa_level_down", FA_LEVEL_DOWN);
        MAP.put("fa_level_up", FA_LEVEL_UP);
        MAP.put("fa_life_bouy", FA_LIFE_BOUY);
        MAP.put("fa_life_buoy", FA_LIFE_BUOY);
        MAP.put("fa_life_ring", FA_LIFE_RING);
        MAP.put("fa_life_saver", FA_LIFE_SAVER);
        MAP.put("fa_lightbulb_o", FA_LIGHTBULB_O);
        MAP.put("fa_line_chart", FA_LINE_CHART);
        MAP.put("fa_link", FA_LINK);
        MAP.put("fa_linkedin", FA_LINKEDIN);
        MAP.put("fa_linkedin_square", FA_LINKEDIN_SQUARE);
        MAP.put("fa_linux", FA_LINUX);
        MAP.put("fa_list", FA_LIST);
        MAP.put("fa_list_alt", FA_LIST_ALT);
        MAP.put("fa_list_ol", FA_LIST_OL);
        MAP.put("fa_list_ul", FA_LIST_UL);
        MAP.put("fa_location_arrow", FA_LOCATION_ARROW);
        MAP.put("fa_lock", FA_LOCK);
        MAP.put("fa_long_arrow_down", FA_LONG_ARROW_DOWN);
        MAP.put("fa_long_arrow_left", FA_LONG_ARROW_LEFT);
        MAP.put("fa_long_arrow_right", FA_LONG_ARROW_RIGHT);
        MAP.put("fa_long_arrow_up", FA_LONG_ARROW_UP);
        MAP.put("fa_magic", FA_MAGIC);
        MAP.put("fa_magnet", FA_MAGNET);
        MAP.put("fa_mail_forward", FA_MAIL_FORWARD);
        MAP.put("fa_mail_reply", FA_MAIL_REPLY);
        MAP.put("fa_mail_reply_all", FA_MAIL_REPLY_ALL);
        MAP.put("fa_male", FA_MALE);
        MAP.put("fa_map", FA_MAP);
        MAP.put("fa_map_marker", FA_MAP_MARKER);
        MAP.put("fa_map_o", FA_MAP_O);
        MAP.put("fa_map_pin", FA_MAP_PIN);
        MAP.put("fa_map_signs", FA_MAP_SIGNS);
        MAP.put("fa_mars", FA_MARS);
        MAP.put("fa_mars_double", FA_MARS_DOUBLE);
        MAP.put("fa_mars_stroke", FA_MARS_STROKE);
        MAP.put("fa_mars_stroke_h", FA_MARS_STROKE_H);
        MAP.put("fa_mars_stroke_v", FA_MARS_STROKE_V);
        MAP.put("fa_maxcdn", FA_MAXCDN);
        MAP.put("fa_meanpath", FA_MEANPATH);
        MAP.put("fa_medium", FA_MEDIUM);
        MAP.put("fa_medkit", FA_MEDKIT);
        MAP.put("fa_meh_o", FA_MEH_O);
        MAP.put("fa_mercury", FA_MERCURY);
        MAP.put("fa_microphone", FA_MICROPHONE);
        MAP.put("fa_microphone_slash", FA_MICROPHONE_SLASH);
        MAP.put("fa_minus", FA_MINUS);
        MAP.put("fa_minus_circle", FA_MINUS_CIRCLE);
        MAP.put("fa_minus_square", FA_MINUS_SQUARE);
        MAP.put("fa_minus_square_o", FA_MINUS_SQUARE_O);
        MAP.put("fa_mobile", FA_MOBILE);
        MAP.put("fa_mobile_phone", FA_MOBILE_PHONE);
        MAP.put("fa_money", FA_MONEY);
        MAP.put("fa_moon_o", FA_MOON_O);
        MAP.put("fa_mortar_board", FA_MORTAR_BOARD);
        MAP.put("fa_motorcycle", FA_MOTORCYCLE);
        MAP.put("fa_mouse_pointer", FA_MOUSE_POINTER);
        MAP.put("fa_music", FA_MUSIC);
        MAP.put("fa_navicon", FA_NAVICON);
        MAP.put("fa_neuter", FA_NEUTER);
        MAP.put("fa_newspaper_o", FA_NEWSPAPER_O);
        MAP.put("fa_object_group", FA_OBJECT_GROUP);
        MAP.put("fa_object_ungroup", FA_OBJECT_UNGROUP);
        MAP.put("fa_odnoklassniki", FA_ODNOKLASSNIKI);
        MAP.put("fa_odnoklassniki_square", FA_ODNOKLASSNIKI_SQUARE);
        MAP.put("fa_opencart", FA_OPENCART);
        MAP.put("fa_openid", FA_OPENID);
        MAP.put("fa_opera", FA_OPERA);
        MAP.put("fa_optin_monster", FA_OPTIN_MONSTER);
        MAP.put("fa_outdent", FA_OUTDENT);
        MAP.put("fa_pagelines", FA_PAGELINES);
        MAP.put("fa_paint_brush", FA_PAINT_BRUSH);
        MAP.put("fa_paper_plane", FA_PAPER_PLANE);
        MAP.put("fa_paper_plane_o", FA_PAPER_PLANE_O);
        MAP.put("fa_paperclip", FA_PAPERCLIP);
        MAP.put("fa_paragraph", FA_PARAGRAPH);
        MAP.put("fa_paste", FA_PASTE);
        MAP.put("fa_pause", FA_PAUSE);
        MAP.put("fa_paw", FA_PAW);
        MAP.put("fa_paypal", FA_PAYPAL);
        MAP.put("fa_pencil", FA_PENCIL);
        MAP.put("fa_pencil_square", FA_PENCIL_SQUARE);
        MAP.put("fa_pencil_square_o", FA_PENCIL_SQUARE_O);
        MAP.put("fa_phone", FA_PHONE);
        MAP.put("fa_phone_square", FA_PHONE_SQUARE);
        MAP.put("fa_photo", FA_PHOTO);
        MAP.put("fa_picture_o", FA_PICTURE_O);
        MAP.put("fa_pie_chart", FA_PIE_CHART);
        MAP.put("fa_pied_piper", FA_PIED_PIPER);
        MAP.put("fa_pied_piper_alt", FA_PIED_PIPER_ALT);
        MAP.put("fa_pinterest", FA_PINTEREST);
        MAP.put("fa_pinterest_p", FA_PINTEREST_P);
        MAP.put("fa_pinterest_square", FA_PINTEREST_SQUARE);
        MAP.put("fa_plane", FA_PLANE);
        MAP.put("fa_play", FA_PLAY);
        MAP.put("fa_play_circle", FA_PLAY_CIRCLE);
        MAP.put("fa_play_circle_o", FA_PLAY_CIRCLE_O);
        MAP.put("fa_plug", FA_PLUG);
        MAP.put("fa_plus", FA_PLUS);
        MAP.put("fa_plus_circle", FA_PLUS_CIRCLE);
        MAP.put("fa_plus_square", FA_PLUS_SQUARE);
        MAP.put("fa_plus_square_o", FA_PLUS_SQUARE_O);
        MAP.put("fa_power_off", FA_POWER_OFF);
        MAP.put("fa_print", FA_PRINT);
        MAP.put("fa_puzzle_piece", FA_PUZZLE_PIECE);
        MAP.put("fa_qq", FA_QQ);
        MAP.put("fa_qrcode", FA_QRCODE);
        MAP.put("fa_question", FA_QUESTION);
        MAP.put("fa_question_circle", FA_QUESTION_CIRCLE);
        MAP.put("fa_quote_left", FA_QUOTE_LEFT);
        MAP.put("fa_quote_right", FA_QUOTE_RIGHT);
        MAP.put("fa_ra", FA_RA);
        MAP.put("fa_random", FA_RANDOM);
        MAP.put("fa_rebel", FA_REBEL);
        MAP.put("fa_recycle", FA_RECYCLE);
        MAP.put("fa_reddit", FA_REDDIT);
        MAP.put("fa_reddit_square", FA_REDDIT_SQUARE);
        MAP.put("fa_refresh", FA_REFRESH);
        MAP.put("fa_registered", FA_REGISTERED);
        MAP.put("fa_remove", FA_REMOVE);
        MAP.put("fa_renren", FA_RENREN);
        MAP.put("fa_reorder", FA_REORDER);
        MAP.put("fa_repeat", FA_REPEAT);
        MAP.put("fa_reply", FA_REPLY);
        MAP.put("fa_reply_all", FA_REPLY_ALL);
        MAP.put("fa_retweet", FA_RETWEET);
        MAP.put("fa_rmb", FA_RMB);
        MAP.put("fa_road", FA_ROAD);
        MAP.put("fa_rocket", FA_ROCKET);
        MAP.put("fa_rotate_left", FA_ROTATE_LEFT);
        MAP.put("fa_rotate_right", FA_ROTATE_RIGHT);
        MAP.put("fa_rouble", FA_ROUBLE);
        MAP.put("fa_rss", FA_RSS);
        MAP.put("fa_rss_square", FA_RSS_SQUARE);
        MAP.put("fa_rub", FA_RUB);
        MAP.put("fa_ruble", FA_RUBLE);
        MAP.put("fa_rupee", FA_RUPEE);
        MAP.put("fa_safari", FA_SAFARI);
        MAP.put("fa_save", FA_SAVE);
        MAP.put("fa_scissors", FA_SCISSORS);
        MAP.put("fa_search", FA_SEARCH);
        MAP.put("fa_search_minus", FA_SEARCH_MINUS);
        MAP.put("fa_search_plus", FA_SEARCH_PLUS);
        MAP.put("fa_sellsy", FA_SELLSY);
        MAP.put("fa_send", FA_SEND);
        MAP.put("fa_send_o", FA_SEND_O);
        MAP.put("fa_server", FA_SERVER);
        MAP.put("fa_share", FA_SHARE);
        MAP.put("fa_share_alt", FA_SHARE_ALT);
        MAP.put("fa_share_alt_square", FA_SHARE_ALT_SQUARE);
        MAP.put("fa_share_square", FA_SHARE_SQUARE);
        MAP.put("fa_share_square_o", FA_SHARE_SQUARE_O);
        MAP.put("fa_shekel", FA_SHEKEL);
        MAP.put("fa_sheqel", FA_SHEQEL);
        MAP.put("fa_shield", FA_SHIELD);
        MAP.put("fa_ship", FA_SHIP);
        MAP.put("fa_shirtsinbulk", FA_SHIRTSINBULK);
        MAP.put("fa_shopping_cart", FA_SHOPPING_CART);
        MAP.put("fa_sign_in", FA_SIGN_IN);
        MAP.put("fa_sign_out", FA_SIGN_OUT);
        MAP.put("fa_signal", FA_SIGNAL);
        MAP.put("fa_simplybuilt", FA_SIMPLYBUILT);
        MAP.put("fa_sitemap", FA_SITEMAP);
        MAP.put("fa_skyatlas", FA_SKYATLAS);
        MAP.put("fa_skype", FA_SKYPE);
        MAP.put("fa_slack", FA_SLACK);
        MAP.put("fa_sliders", FA_SLIDERS);
        MAP.put("fa_slideshare", FA_SLIDESHARE);
        MAP.put("fa_smile_o", FA_SMILE_O);
        MAP.put("fa_soccer_ball_o", FA_SOCCER_BALL_O);
        MAP.put("fa_sort", FA_SORT);
        MAP.put("fa_sort_alpha_asc", FA_SORT_ALPHA_ASC);
        MAP.put("fa_sort_alpha_desc", FA_SORT_ALPHA_DESC);
        MAP.put("fa_sort_amount_asc", FA_SORT_AMOUNT_ASC);
        MAP.put("fa_sort_amount_desc", FA_SORT_AMOUNT_DESC);
        MAP.put("fa_sort_asc", FA_SORT_ASC);
        MAP.put("fa_sort_desc", FA_SORT_DESC);
        MAP.put("fa_sort_down", FA_SORT_DOWN);
        MAP.put("fa_sort_numeric_asc", FA_SORT_NUMERIC_ASC);
        MAP.put("fa_sort_numeric_desc", FA_SORT_NUMERIC_DESC);
        MAP.put("fa_sort_up", FA_SORT_UP);
        MAP.put("fa_soundcloud", FA_SOUNDCLOUD);
        MAP.put("fa_space_shuttle", FA_SPACE_SHUTTLE);
        MAP.put("fa_spinner", FA_SPINNER);
        MAP.put("fa_spoon", FA_SPOON);
        MAP.put("fa_spotify", FA_SPOTIFY);
        MAP.put("fa_square", FA_SQUARE);
        MAP.put("fa_square_o", FA_SQUARE_O);
        MAP.put("fa_stack_exchange", FA_STACK_EXCHANGE);
        MAP.put("fa_stack_overflow", FA_STACK_OVERFLOW);
        MAP.put("fa_star", FA_STAR);
        MAP.put("fa_star_half", FA_STAR_HALF);
        MAP.put("fa_star_half_empty", FA_STAR_HALF_EMPTY);
        MAP.put("fa_star_half_full", FA_STAR_HALF_FULL);
        MAP.put("fa_star_half_o", FA_STAR_HALF_O);
        MAP.put("fa_star_o", FA_STAR_O);
        MAP.put("fa_steam", FA_STEAM);
        MAP.put("fa_steam_square", FA_STEAM_SQUARE);
        MAP.put("fa_step_backward", FA_STEP_BACKWARD);
        MAP.put("fa_step_forward", FA_STEP_FORWARD);
        MAP.put("fa_stethoscope", FA_STETHOSCOPE);
        MAP.put("fa_sticky_note", FA_STICKY_NOTE);
        MAP.put("fa_sticky_note_o", FA_STICKY_NOTE_O);
        MAP.put("fa_stop", FA_STOP);
        MAP.put("fa_street_view", FA_STREET_VIEW);
        MAP.put("fa_strikethrough", FA_STRIKETHROUGH);
        MAP.put("fa_stumbleupon", FA_STUMBLEUPON);
        MAP.put("fa_stumbleupon_circle", FA_STUMBLEUPON_CIRCLE);
        MAP.put("fa_subscript", FA_SUBSCRIPT);
        MAP.put("fa_subway", FA_SUBWAY);
        MAP.put("fa_suitcase", FA_SUITCASE);
        MAP.put("fa_sun_o", FA_SUN_O);
        MAP.put("fa_superscript", FA_SUPERSCRIPT);
        MAP.put("fa_support", FA_SUPPORT);
        MAP.put("fa_table", FA_TABLE);
        MAP.put("fa_tablet", FA_TABLET);
        MAP.put("fa_tachometer", FA_TACHOMETER);
        MAP.put("fa_tag", FA_TAG);
        MAP.put("fa_tags", FA_TAGS);
        MAP.put("fa_tasks", FA_TASKS);
        MAP.put("fa_taxi", FA_TAXI);
        MAP.put("fa_television", FA_TELEVISION);
        MAP.put("fa_tencent_weibo", FA_TENCENT_WEIBO);
        MAP.put("fa_terminal", FA_TERMINAL);
        MAP.put("fa_text_height", FA_TEXT_HEIGHT);
        MAP.put("fa_text_width", FA_TEXT_WIDTH);
        MAP.put("fa_th", FA_TH);
        MAP.put("fa_th_large", FA_TH_LARGE);
        MAP.put("fa_th_list", FA_TH_LIST);
        MAP.put("fa_thumb_tack", FA_THUMB_TACK);
        MAP.put("fa_thumbs_down", FA_THUMBS_DOWN);
        MAP.put("fa_thumbs_o_down", FA_THUMBS_O_DOWN);
        MAP.put("fa_thumbs_o_up", FA_THUMBS_O_UP);
        MAP.put("fa_thumbs_up", FA_THUMBS_UP);
        MAP.put("fa_ticket", FA_TICKET);
        MAP.put("fa_times", FA_TIMES);
        MAP.put("fa_times_circle", FA_TIMES_CIRCLE);
        MAP.put("fa_times_circle_o", FA_TIMES_CIRCLE_O);
        MAP.put("fa_tint", FA_TINT);
        MAP.put("fa_toggle_down", FA_TOGGLE_DOWN);
        MAP.put("fa_toggle_left", FA_TOGGLE_LEFT);
        MAP.put("fa_toggle_off", FA_TOGGLE_OFF);
        MAP.put("fa_toggle_on", FA_TOGGLE_ON);
        MAP.put("fa_toggle_right", FA_TOGGLE_RIGHT);
        MAP.put("fa_toggle_up", FA_TOGGLE_UP);
        MAP.put("fa_trademark", FA_TRADEMARK);
        MAP.put("fa_train", FA_TRAIN);
        MAP.put("fa_transgender", FA_TRANSGENDER);
        MAP.put("fa_transgender_alt", FA_TRANSGENDER_ALT);
        MAP.put("fa_trash", FA_TRASH);
        MAP.put("fa_trash_o", FA_TRASH_O);
        MAP.put("fa_tree", FA_TREE);
        MAP.put("fa_trello", FA_TRELLO);
        MAP.put("fa_tripadvisor", FA_TRIPADVISOR);
        MAP.put("fa_trophy", FA_TROPHY);
        MAP.put("fa_truck", FA_TRUCK);
        MAP.put("fa_try", FA_TRY);
        MAP.put("fa_tty", FA_TTY);
        MAP.put("fa_tumblr", FA_TUMBLR);
        MAP.put("fa_tumblr_square", FA_TUMBLR_SQUARE);
        MAP.put("fa_turkish_lira", FA_TURKISH_LIRA);
        MAP.put("fa_tv", FA_TV);
        MAP.put("fa_twitch", FA_TWITCH);
        MAP.put("fa_twitter", FA_TWITTER);
        MAP.put("fa_twitter_square", FA_TWITTER_SQUARE);
        MAP.put("fa_umbrella", FA_UMBRELLA);
        MAP.put("fa_underline", FA_UNDERLINE);
        MAP.put("fa_undo", FA_UNDO);
        MAP.put("fa_university", FA_UNIVERSITY);
        MAP.put("fa_unlink", FA_UNLINK);
        MAP.put("fa_unlock", FA_UNLOCK);
        MAP.put("fa_unlock_alt", FA_UNLOCK_ALT);
        MAP.put("fa_unsorted", FA_UNSORTED);
        MAP.put("fa_upload", FA_UPLOAD);
        MAP.put("fa_usd", FA_USD);
        MAP.put("fa_user", FA_USER);
        MAP.put("fa_user_md", FA_USER_MD);
        MAP.put("fa_user_plus", FA_USER_PLUS);
        MAP.put("fa_user_secret", FA_USER_SECRET);
        MAP.put("fa_user_times", FA_USER_TIMES);
        MAP.put("fa_users", FA_USERS);
        MAP.put("fa_venus", FA_VENUS);
        MAP.put("fa_venus_double", FA_VENUS_DOUBLE);
        MAP.put("fa_venus_mars", FA_VENUS_MARS);
        MAP.put("fa_viacoin", FA_VIACOIN);
        MAP.put("fa_video_camera", FA_VIDEO_CAMERA);
        MAP.put("fa_vimeo", FA_VIMEO);
        MAP.put("fa_vimeo_square", FA_VIMEO_SQUARE);
        MAP.put("fa_vine", FA_VINE);
        MAP.put("fa_vk", FA_VK);
        MAP.put("fa_volume_down", FA_VOLUME_DOWN);
        MAP.put("fa_volume_off", FA_VOLUME_OFF);
        MAP.put("fa_volume_up", FA_VOLUME_UP);
        MAP.put("fa_warning", FA_WARNING);
        MAP.put("fa_wechat", FA_WECHAT);
        MAP.put("fa_weibo", FA_WEIBO);
        MAP.put("fa_weixin", FA_WEIXIN);
        MAP.put("fa_whatsapp", FA_WHATSAPP);
        MAP.put("fa_wheelchair", FA_WHEELCHAIR);
        MAP.put("fa_wifi", FA_WIFI);
        MAP.put("fa_wikipedia_w", FA_WIKIPEDIA_W);
        MAP.put("fa_windows", FA_WINDOWS);
        MAP.put("fa_won", FA_WON);
        MAP.put("fa_wordpress", FA_WORDPRESS);
        MAP.put("fa_wrench", FA_WRENCH);
        MAP.put("fa_xing", FA_XING);
        MAP.put("fa_xing_square", FA_XING_SQUARE);
        MAP.put("fa_y_combinator", FA_Y_COMBINATOR);
        MAP.put("fa_y_combinator_square", FA_Y_COMBINATOR_SQUARE);
        MAP.put("fa_yahoo", FA_YAHOO);
        MAP.put("fa_yc", FA_YC);
        MAP.put("fa_yc_square", FA_YC_SQUARE);
        MAP.put("fa_yelp", FA_YELP);
        MAP.put("fa_yen", FA_YEN);
        MAP.put("fa_youtube", FA_YOUTUBE);
        MAP.put("fa_youtube_play", FA_YOUTUBE_PLAY);
        MAP.put("fa_youtube_square", FA_YOUTUBE_SQUARE);
    }

}
